### ISSUE TITLE
Time setting requires a reboot to take effect

### ISSUE THREAD

**Issue by vadi2** [rishuinfinity/WallpaperSwitcher#1]
It doesn't seem to be applying the time setting right away:

https://user-images.githubusercontent.com/110988/153578778-5f7c97ff-3ae5-494f-9840-acb07369ae1b.mp4

**Comment by rishuinfinity** [comment]
Well I did that intentionally, and also I have mentioned it on settings that reload is required for changes to take effect.

**Comment by rishuinfinity** [comment]
Hey @vadi2 . I've updated the extension with the feature to:
* right-away update of wallpaper change timeout.
* right-away update of wallpaper path
Still tho it needs previous timeout to end to start new timeout, but I guess this might be enough. Hope you would find it easier to use now.
Thanks for your suggestion tho.
