### ISSUE TITLE
Not switching wallpapers

### ISSUE THREAD

**Issue by Chantology** [rishuinfinity/WallpaperSwitcher#20]
Hello, I downloaded this extension yesterday and it seems like this addon is not switching wallpapers. Please find these images for reference: 

![Screenshot from 2023-02-17 12-42-25](https://user-images.githubusercontent.com/50327807/219645648-f56754c3-57b8-4264-ad07-d453da0493b3.png)
![Screenshot from 2023-02-17 12-42-04](https://user-images.githubusercontent.com/50327807/219645650-6eee3ffc-5c57-42b1-a882-b8e335002324.png)
![Screenshot from 2023-02-17 12-39-54](https://user-images.githubusercontent.com/50327807/219645653-cd215eff-5e57-49ce-a75f-19f17900add1.png)

If the Refresh Time is 60 it means that it should switch every minute right? Did I muss anything? The install process in the browser worked pretty well. 

I am kind of new using Linux so I am happy for any help. 

Best, 
Chan

**Comment by rishuinfinity** [comment]
The default Wallpaper folder is set to "/usr/share/backgrounds", but in fedora, the folder is different and also only contains webp images.

The best thing you can do is to set the Wallpaper folder to the path where you have your collection of wallpapers. Then it should work fine

**Comment by Chantology** [comment]
it's working, thanks a lot!

**Comment by rishuinfinity** [comment]
: )
