### ISSUE TITLE
No longer switches Gnome 42 dark theme (Fix included)

### ISSUE THREAD

**Issue by lukedupin** [rishuinfinity/WallpaperSwitcher#3]
Gnome 42 now has a Light and Dark theme under appearance. The light theme still works, but dark theme does not. There is a new registry key for dark theme background URIs.

If the following code is added to the **setPictureUriOfSettingsObject** function, both light and dark theme work again.

```
  if (bsettings.is_writable("picture-uri-dark")) {
    // Set a new Background-Image (should show up immediately):
    let rc = bsettings.set_string("picture-uri-dark", path);
    if (rc) {
      Gio.Settings.sync(); // Necessary: http://stackoverflow.com/questions/9985140
    } else {
      saveExceptionLog("Could not set lock screen wallpaper.");
    }
  } else {
    saveExceptionLog("Could not set wallpaper.");
  }
```

I tested this change on my local and am happily switching backgrounds on both themes.

**Comment by rishuinfinity** [comment]
Thanks a lot. Ypu've really saved a lot of my time. I haven't yet tried gnome 42 (been waiting for ubuntu 22.04 release), so I didn't know about the issue. I'll try to install it on a VM and try to update the extension as soon as possible.

**Comment by lukedupin** [comment]
Arch linux =)

**Comment by rishuinfinity** [comment]
:bowing_man: respect++
