### ISSUE TITLE
Wallpapers are only switched on Dark/light mode, not both.

### ISSUE THREAD

**Issue by Thunderschnozzle** [rishuinfinity/WallpaperSwitcher#5]
As the title describes, when the extension switches to a new wallpaper it only does it for the desktop and lock screen of either the light or dark theme (whichever the user is using at the time), but not both. Could you make it so it will change it for both (which is what happens if the user sets up a wallpaper manually)?

**Comment by Thunderschnozzle** [comment]
Yep, I figured that was probably done intentionally. I have a very specialized need for this functionality, but let me explain anyways. I have a large collection of wallpapers (probably around 1500, which I've downloaded in bulk from InterfaceLIFT). Sometimes when I see a wallpaper for the first time after it has been applied by your extension I don't like it and, therefore, I want to delete it from my drive. However, finding the wallpaper within such large collection can prove to be a daunting task. So, I want to use the "Background" option under the "Appearance" section of the GNOME Tweaks app to see the name of the wallpaper currently being applied. The problem is that Tweaks only shows the name of the wallpaper being applied for the light theme and I like to use the dark theme. That is my problem. Unless you happen to know how to "point" the Tweaks app to look at the dark theme wallpaper, or how to otherwise find the name of the currently applied wallpaper, then applying the wallpaper to both themes is the only option I could think of to solve my problem.

**Comment by rishuinfinity** [comment]
Ah I completely understand your problem, and I face them too to be honest. 🤜🤛.
I have a plan to add the name thing on the preferences window. But currently I am occupied on another upcoming extension namely Wallpaper Overlay😅😅. You can checkout its beta version on my github.

Anyways, as an alternative to gnome-tweaks, you can use dconf-editor. When you search for picture-uri, and picture-uri-dark, then you can get the picture names from the search list.

Another alternative is that if you know a little bit of coding, you can modify the extension yourself by editing the set_wallpaper function in lib.js
The extension files are present in /local/
